networks:
  microservices_net:
    driver: bridge

services:
  postgres-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-order_db}
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-order_db}',
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - microservices_net

  mongodb:
    image: mongo:7.0
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - microservices_net

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '${REDIS_PORT:-6379}:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - microservices_net

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq_broker
    ports:
      - '5672:5672' # AMQP protocol for services
      - '15672:15672' # Management Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'check_port_connectivity']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - microservices_net

  notification-service:
    container_name: notification-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${NOTIFICATION_SERVICE_PORT:-3002}:3002'
    environment:
      PORT: ${NOTIFICATION_SERVICE_PORT:-3002}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      NOTIFICATION_QUEUE_NAME: ${NOTIFICATION_QUEUE_NAME:-queue:notifications}
      RABBITMQ_URL: ${RABBITMQ_URL}
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - microservices_net

  insight-pulse-service:
    build:
      context: ./insight-pulse-service
      dockerfile: Dockerfile
    ports:
      - '${INSIGHT_PULSE_PORT:-3001}:3001'
    environment:
      PORT: ${INSIGHT_PULSE_PORT:-3001}
      MONGO_URI: ${MONGO_URI:-mongodb://mongodb:27017/insight_pulse}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - microservices_net

  order-inventory-service:
    build:
      context: ./order-inventory-service
      dockerfile: Dockerfile
    ports:
      - '${ORDER_SERVICE_PORT:-3000}:3000'
    environment:
      PORT: ${ORDER_SERVICE_PORT:-3000}
      DATABASE_URL: ${DATABASE_URL:-postgresql://user:password@postgres-db:5432/order_db}
      ANALYTICS_SERVICE_URL: ${ANALYTICS_SERVICE_URL:-http://insight-pulse-service:3001}
      NOTIFICATION_SERVICE_URL: ${NOTIFICATION_SERVICE_URL:-http://notification-service:3002}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - microservices_net
